@startuml
skinparam defaultFontName Helvetica

interface Descuento {
    + aplicarDescuento()
}

Descuento <|.. D1
Descuento <|.. D2

class AppChat {
    +login()
}

hide AppChat attributes
note top of AppChat : Controlador
AppChat -left->  Descuento

class CatalogoUsuarios {
    +getUsuario()
    +addUsuario()
}

hide CatalogoUsuarios attributes
AppChat *-- "1" CatalogoUsuarios

class Usuario {
    - nombre: String
    - email: String
    - telefono: String
    - premium: Boolean
}

CatalogoUsuarios *-- "0..*" Usuario

class Contacto {
    - nombre: String
    - telefono : String
}

Usuario *-right- Contacto

class Grupo {
    - nombre: String
    - miembros: Set<Contacto>
    - agregarContacto()
}

class Mensaje {
    - texto: String
    - emisor: String
    - receptor: String
    - fechaHora: Date
}

Usuario -right- Mensaje

Usuario -down- Grupo

interface Filtro {
    + aplicarDescuento()
}

Filtro  <|.. FiltroTexto
Filtro  <|.left. FiltroContacto
Filtro  <|.. FiltroTelefono

Usuario -left->  Filtro


@enduml
